# Generated by Django 4.2 on 2025-01-24 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0015_storeproduct_operatorpoints'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operatorpoints',
            name='operator',
        ),
        migrations.DeleteModel(
            name='StoreProduct',
        ),
        migrations.DeleteModel(
            name='OperatorPoints',
        ),
    ]
